### PR TITLE
Fix issue 298: support browsers that report sub-pixels

### PR DESCRIPTION
**Pull request by andreacampi**

### CODE REVIEW

**Comment by bramstein** [comment]
I doubt this is the final solution for subpixel support, but the code seems solid.

**Comment by andreacampi** [comment]
Yeah, I was almost surprised it was relatively easy. But in all our testing, it's pretty solid.
I've had some reports of problems on IE9, I'm going to retest it there.

**Comment by andreacampi** [comment]
As we expected, some more corner cases.

Apparently this latest bug escaped my testing because it only affected layout "sometimes"; it mostly resulted in some grids being penalized, and that's how we found it.

The fix is on my branch: https://github.com/andreacampi/treesaver/tree/issue-298-one-more-fix
I'll send a pull request when I'm satisfied it's reliable; I also need to retest IE9.

**Comment by andreacampi** [comment]
Just to keep you updated:

I'm afraid IE9 is more problematic (surprise!) since `getBoundingClientRect` returns whole pixels _and_ both that method and offset\* round up (as opposed to every other browser which rounds down).
The best bet would be using `getComputedStyle`, probably going through a virtual accessor that knows which one to use.

But that's more than I can tackle right, especially since unit tests are already broken on IE9.

For the time being, the best bet is to use pixels on IE.

**Pull request merged**
